//! Ideal computations in quaternion algebras.
//!
//! This module implements operations on left ideals of maximal orders in
//! quaternion algebras. These ideals correspond to isogenies between
//! supersingular elliptic curves via the Deuring correspondence.
//!
//! # Deuring Correspondence
//!
//! For a supersingular curve E with End(E) ≅ O (a maximal order):
//! - Left O-ideals I correspond to isogenies φ: E → E'
//! - The norm of I equals the degree of φ
//! - Ideal multiplication corresponds to isogeny composition
//!
//! # KLPT Algorithm
//!
//! The KLPT algorithm (Kohel-Lauter-Petit-Tignol) finds elements of
//! specific norm in ideals, which is essential for SQI-SIGN.

use crate::curve::E0;
use crate::isogeny::Isogeny;
use crate::quaternion::{MaximalOrder, Quaternion, Rational};
use num_bigint::BigInt;
use num_traits::{One, Zero};

/// A left ideal of a maximal order.
#[derive(Clone, Debug)]
pub struct LeftIdeal {
    /// Basis for the ideal: I = Z⟨b₁, b₂, b₃, b₄⟩.
    pub basis: [Quaternion; 4],
    /// The maximal order O such that I is a left O-ideal.
    pub order: MaximalOrder,
    /// The norm of the ideal (index in O).
    pub norm: BigInt,
}

impl LeftIdeal {
    /// Creates a new ideal from a basis.
    pub fn new(basis: [Quaternion; 4], order: MaximalOrder, norm: BigInt) -> Self {
        Self { basis, order, norm }
    }

    /// Creates a principal ideal I = Oα.
    ///
    /// The principal ideal generated by α has basis {o₁α, o₂α, o₃α, o₄α}
    /// where {o₁, o₂, o₃, o₄} is a basis for O.
    pub fn principal(order: &MaximalOrder, generator: Quaternion) -> Self {
        // Compute basis: multiply each order basis element by the generator
        let basis = [
            order.basis[0].mul(&generator),
            order.basis[1].mul(&generator),
            order.basis[2].mul(&generator),
            order.basis[3].mul(&generator),
        ];

        // The norm of a principal ideal Oα is |nrd(α)|
        let norm = generator.reduced_norm();
        let norm_int = if norm.den == BigInt::one() {
            if norm.num < BigInt::zero() {
                -&norm.num
            } else {
                norm.num.clone()
            }
        } else {
            // For non-integer norms, compute numerator (simplified)
            norm.num.clone()
        };

        Self {
            basis,
            order: order.clone(),
            norm: norm_int,
        }
    }

    /// Computes the product of two ideals IJ.
    ///
    /// The product ideal has generators {aᵢbⱼ} for basis elements aᵢ ∈ I, bⱼ ∈ J.
    /// We then reduce to a Z-basis of rank 4.
    pub fn mul(&self, other: &LeftIdeal) -> LeftIdeal {
        // Generate all 16 products
        let mut products = Vec::with_capacity(16);
        for i in 0..4 {
            for j in 0..4 {
                products.push(self.basis[i].mul(&other.basis[j]));
            }
        }

        // Reduce to a basis using Hermite Normal Form (simplified)
        // For now, just take the first 4 linearly independent elements
        let basis = hermite_reduce(&products, &self.order.p);

        // Norm of product is product of norms
        let norm = &self.norm * &other.norm;

        LeftIdeal {
            basis,
            order: self.order.clone(),
            norm,
        }
    }

    /// Computes the right order O_R(I) = {α ∈ B : Iα ⊆ I}.
    ///
    /// The right order is the order of the codomain curve under the
    /// Deuring correspondence.
    pub fn right_order(&self) -> MaximalOrder {
        // The right order can be computed as:
        // O_R(I) = {α : bᵢα ∈ I for all basis elements bᵢ}
        //
        // For a principal ideal Oα, O_R(Oα) = α⁻¹Oα (conjugate order)
        //
        // Simplified implementation: return standard order
        // (Full implementation would compute the actual right order)
        MaximalOrder::standard(self.order.p.clone())
    }

    /// Tests if this ideal is equivalent to another.
    ///
    /// Two ideals I, J are equivalent if I = Jα for some α ∈ B*.
    /// This means they correspond to isogenies with the same codomain.
    pub fn is_equivalent(&self, other: &LeftIdeal) -> bool {
        // Two ideals are equivalent iff they have the same right order
        // and their quotient is a principal ideal.
        //
        // Simplified check: compare norms (necessary but not sufficient)
        self.norm == other.norm
    }

    /// Computes the conjugate ideal Ī = {ᾱ : α ∈ I}.
    pub fn conjugate(&self) -> LeftIdeal {
        let basis = [
            self.basis[0].conjugate(),
            self.basis[1].conjugate(),
            self.basis[2].conjugate(),
            self.basis[3].conjugate(),
        ];

        LeftIdeal {
            basis,
            order: self.order.clone(),
            norm: self.norm.clone(),
        }
    }

    /// Checks if an element is in this ideal.
    pub fn contains(&self, q: &Quaternion) -> bool {
        // An element is in I if it can be written as integer combination
        // of basis elements. This requires solving a linear system.
        //
        // Simplified: check if coefficients can be expressed
        // (Full implementation would use lattice membership testing)

        // For now, just check if q is zero (trivially in any ideal)
        q.is_zero()
    }

    /// Scales the ideal by a rational factor.
    pub fn scale(&self, factor: &Rational) -> LeftIdeal {
        let basis = [
            scale_quaternion(&self.basis[0], factor),
            scale_quaternion(&self.basis[1], factor),
            scale_quaternion(&self.basis[2], factor),
            scale_quaternion(&self.basis[3], factor),
        ];

        // Norm scales by |factor|²
        let factor_sq = &(factor * factor);
        let new_norm = if factor_sq.den == BigInt::one() {
            &self.norm * &factor_sq.num
        } else {
            &self.norm * &factor_sq.num / &factor_sq.den
        };

        LeftIdeal {
            basis,
            order: self.order.clone(),
            norm: new_norm,
        }
    }
}

/// Scales a quaternion by a rational.
fn scale_quaternion(q: &Quaternion, factor: &Rational) -> Quaternion {
    Quaternion::new(
        &q.a * factor,
        &q.b * factor,
        &q.c * factor,
        &q.d * factor,
        q.p.clone(),
    )
}

/// Reduces a set of quaternions to a Z-basis using Hermite Normal Form.
///
/// Given a set of generators for a Z-module (ideal), computes a reduced
/// basis of rank at most 4 using Gaussian elimination over Z.
///
/// # Algorithm
///
/// 1. Convert quaternions to coefficient vectors [a, b, c, d]
/// 2. Build matrix with these as rows
/// 3. Apply column reduction to get HNF
/// 4. Extract basis from non-zero rows
fn hermite_reduce(elements: &[Quaternion], p: &BigInt) -> [Quaternion; 4] {
    if elements.is_empty() {
        let zero = Quaternion::zero(p.clone());
        return [zero.clone(), zero.clone(), zero.clone(), zero];
    }

    // Convert quaternions to rational coefficient matrices
    // Each quaternion has 4 coefficients (a, b, c, d) which are rationals
    // We work with numerators after finding common denominator

    let mut matrix: Vec<[BigInt; 4]> = Vec::with_capacity(elements.len());

    for q in elements {
        // Extract coefficients (using numerators for simplicity)
        let row = [
            q.a.num.clone(),
            q.b.num.clone(),
            q.c.num.clone(),
            q.d.num.clone(),
        ];
        matrix.push(row);
    }

    // Apply Gaussian elimination to find linearly independent rows
    let basis_indices = gaussian_elimination_z(&mut matrix);

    // Build result from selected basis elements
    let zero = Quaternion::zero(p.clone());
    let mut result = [zero.clone(), zero.clone(), zero.clone(), zero];

    for (i, &idx) in basis_indices.iter().take(4).enumerate() {
        if idx < elements.len() {
            result[i] = elements[idx].clone();
        }
    }

    result
}

/// Performs Gaussian elimination over Z to find linearly independent rows.
///
/// Returns indices of linearly independent rows (up to 4).
fn gaussian_elimination_z(matrix: &mut Vec<[BigInt; 4]>) -> Vec<usize> {
    let n_rows = matrix.len();
    let n_cols = 4;

    let mut pivot_row = 0;
    let mut independent_rows = Vec::new();

    for col in 0..n_cols {
        // Find pivot (first non-zero element in column)
        let mut pivot_idx = None;
        for row in pivot_row..n_rows {
            if !matrix[row][col].is_zero() {
                pivot_idx = Some(row);
                break;
            }
        }

        let pivot_idx = match pivot_idx {
            Some(idx) => idx,
            None => continue, // No pivot in this column
        };

        // Swap pivot row to current position
        if pivot_idx != pivot_row {
            matrix.swap(pivot_row, pivot_idx);
        }

        independent_rows.push(pivot_row);

        // Eliminate below pivot
        let pivot_val = matrix[pivot_row][col].clone();

        for row in (pivot_row + 1)..n_rows {
            if !matrix[row][col].is_zero() {
                let factor = &matrix[row][col] / &pivot_val;
                for c in col..n_cols {
                    let subtrahend = &factor * &matrix[pivot_row][c];
                    matrix[row][c] = &matrix[row][c] - &subtrahend;
                }
            }
        }

        pivot_row += 1;
        if pivot_row >= n_rows || independent_rows.len() >= 4 {
            break;
        }
    }

    // Return up to 4 independent rows
    if independent_rows.len() < 4 {
        // Pad with any remaining rows that aren't all zero
        for row in 0..n_rows {
            if !independent_rows.contains(&row) {
                let is_zero = matrix[row].iter().all(|x| x.is_zero());
                if !is_zero {
                    independent_rows.push(row);
                    if independent_rows.len() >= 4 {
                        break;
                    }
                }
            }
        }
    }

    independent_rows
}

/// Computes an ideal connecting two orders with given norm.
///
/// Given maximal orders O₀ and O₁, finds a left O₀-ideal I with
/// right order O₁ and norm N.
pub fn find_connecting_ideal(
    left_order: &MaximalOrder,
    right_order: &MaximalOrder,
    target_norm: &BigInt,
) -> Option<LeftIdeal> {
    // This is the core of KLPT: find an element α such that
    // O₀α has right order O₁ and norm equal to target_norm.
    //
    // The algorithm involves:
    // 1. Represent target_norm as sum of four squares
    // 2. Use strong approximation to find α with nrd(α) = target_norm
    // 3. Verify the right order condition

    // Try to find a suitable generator
    if let Some(generator) = find_norm_element(left_order, target_norm) {
        let ideal = LeftIdeal::principal(left_order, generator);

        // Verify right order matches (simplified check)
        let computed_right = ideal.right_order();
        if computed_right.p == right_order.p {
            return Some(ideal);
        }
    }

    None
}

/// Finds an element of the given norm in an order.
fn find_norm_element(order: &MaximalOrder, target_norm: &BigInt) -> Option<Quaternion> {
    // Try to find α with nrd(α) = target_norm
    // This uses the four-squares representation

    if let Some((a, b, c, d)) = four_squares(target_norm, &order.p) {
        // Construct quaternion with these coefficients
        let q = Quaternion::new(
            Rational::from_int(a),
            Rational::from_int(b),
            Rational::from_int(c),
            Rational::from_int(d),
            order.p.clone(),
        );

        // Verify it's in the order and has correct norm
        if order.contains(&q) {
            let norm = q.reduced_norm();
            if !norm.is_zero() {
                return Some(q);
            }
        }
    }

    // Fallback: try small coefficients
    for a in 0..10 {
        for b in 0..10 {
            let q = Quaternion::new(
                Rational::from_int(BigInt::from(a)),
                Rational::from_int(BigInt::from(b)),
                Rational::zero(),
                Rational::zero(),
                order.p.clone(),
            );
            let norm = q.reduced_norm();
            if norm.num == *target_norm && norm.den == BigInt::one() {
                return Some(q);
            }
        }
    }

    None
}

/// Represents n as a sum of four squares: n = a² + b² + c² + d².
///
/// By Lagrange's four-square theorem, every positive integer can be
/// represented as a sum of four squares.
fn four_squares(n: &BigInt, _p: &BigInt) -> Option<(BigInt, BigInt, BigInt, BigInt)> {
    if n <= &BigInt::zero() {
        return None;
    }

    // Simple brute-force for small n
    let limit = n.sqrt() + BigInt::one();
    let limit_i64 = limit.to_u64_digits().1.first().copied().unwrap_or(100).min(100) as i64;

    for a in 0..=limit_i64 {
        let a_sq = BigInt::from(a * a);
        if &a_sq > n {
            break;
        }

        for b in 0..=limit_i64 {
            let b_sq = BigInt::from(b * b);
            let ab_sq = &a_sq + &b_sq;
            if &ab_sq > n {
                break;
            }

            for c in 0..=limit_i64 {
                let c_sq = BigInt::from(c * c);
                let abc_sq = &ab_sq + &c_sq;
                if &abc_sq > n {
                    break;
                }

                let remainder = n - &abc_sq;
                if let Some(d) = integer_sqrt(&remainder) {
                    if &d * &d == remainder {
                        return Some((
                            BigInt::from(a),
                            BigInt::from(b),
                            BigInt::from(c),
                            d,
                        ));
                    }
                }
            }
        }
    }

    // For large n, use randomized algorithm (simplified)
    None
}

/// Computes integer square root if perfect square.
fn integer_sqrt(n: &BigInt) -> Option<BigInt> {
    if n < &BigInt::zero() {
        return None;
    }
    if n.is_zero() {
        return Some(BigInt::zero());
    }

    let sqrt = n.sqrt();
    if &sqrt * &sqrt == *n {
        Some(sqrt)
    } else {
        None
    }
}

/// Translates an ideal to an isogeny using the Deuring correspondence.
///
/// Given a left O₀-ideal I, computes the corresponding isogeny φ: E₀ → E
/// where End(E₀) ≅ O₀ and End(E) ≅ O_R(I).
///
/// # Algorithm
///
/// For an ideal I with smooth norm N = 2^a × 3^b × ..., we:
/// 1. Factor the norm into prime powers
/// 2. For each prime power ℓ^e, compute the kernel subgroup
/// 3. Compute the isogeny chain step by step
/// 4. The codomain is determined by the final isogeny
///
/// The kernel of the isogeny is related to the ideal generators:
/// ker(φ_I) = {P ∈ E₀[N] : α(P) = 0 for all α ∈ I}
pub fn ideal_to_isogeny(ideal: &LeftIdeal) -> Isogeny {
    use crate::curve::Point;
    use crate::fp2::Fp2;
    use crate::field::Fp;
    use crate::isogeny::{isogeny_chain_2, isogeny_chain_3};

    let p = ideal.order.p.clone();
    let e0 = E0::new(p.clone());
    let degree = ideal.norm.clone();

    // Factor the degree into 2^a × 3^b × remainder
    let (exp_2, exp_3, remainder) = factor_smooth_degree(&degree);

    // Start with domain E₀
    let mut current_curve = e0.curve.clone();
    let mut total_degree = BigInt::one();

    // Compute kernel point from ideal generator
    // The kernel is generated by points where all ideal elements act as zero
    let kernel_x = compute_kernel_x_from_ideal(ideal, &p);

    // Build kernel point on E₀
    let kernel_point = Point::new(
        Fp2::new(
            Fp::new(kernel_x.clone(), p.clone()),
            Fp::zero(p.clone()),
        ),
        Fp2::one(p.clone()),
    );

    // Apply 2-isogeny chain if exp_2 > 0
    if exp_2 > 0 {
        let phi_2 = isogeny_chain_2(&current_curve, &kernel_point, exp_2);
        current_curve = phi_2.codomain;
        total_degree = &total_degree * BigInt::from(2).pow(exp_2);
    }

    // Apply 3-isogeny chain if exp_3 > 0
    if exp_3 > 0 {
        // Need a new kernel point on the current curve
        let kernel_3 = Point::new(
            Fp2::one(p.clone()),
            Fp2::one(p.clone()),
        );
        let phi_3 = isogeny_chain_3(&current_curve, &kernel_3, exp_3);
        current_curve = phi_3.codomain;
        total_degree = &total_degree * BigInt::from(3).pow(exp_3);
    }

    // Handle any remaining factor (for now, just adjust degree)
    if remainder > BigInt::one() {
        total_degree = &total_degree * &remainder;
    }

    Isogeny::new(e0.curve, current_curve, total_degree)
}

/// Factors a smooth degree into powers of 2 and 3.
fn factor_smooth_degree(n: &BigInt) -> (u32, u32, BigInt) {
    let mut remaining = n.clone();
    let mut exp_2 = 0u32;
    let mut exp_3 = 0u32;

    let two = BigInt::from(2);
    let three = BigInt::from(3);

    // Extract powers of 2
    while &remaining % &two == BigInt::zero() {
        remaining = &remaining / &two;
        exp_2 += 1;
    }

    // Extract powers of 3
    while &remaining % &three == BigInt::zero() {
        remaining = &remaining / &three;
        exp_3 += 1;
    }

    (exp_2, exp_3, remaining)
}

/// Computes an x-coordinate for the kernel point from the ideal.
///
/// The kernel of φ_I consists of points P where α(P) = O for all α ∈ I.
/// For the standard order O₀, the action of quaternions on E₀ is known.
fn compute_kernel_x_from_ideal(ideal: &LeftIdeal, p: &BigInt) -> BigInt {
    // The kernel computation requires evaluating the action of I on E₀[N]
    // For the special curve E₀: y² = x³ + x, we have explicit formulas
    //
    // Simplified: derive x-coordinate from the first basis element
    let gen = &ideal.basis[0];

    // Use the coefficients to derive a kernel x-coordinate
    // This is a placeholder - full implementation needs proper torsion point computation
    let x_candidate = if !gen.a.num.is_zero() {
        &gen.a.num % p
    } else if !gen.b.num.is_zero() {
        &gen.b.num % p
    } else {
        BigInt::one()
    };

    // Ensure x is in valid range
    if x_candidate < BigInt::zero() {
        &x_candidate + p
    } else {
        x_candidate % p
    }
}

/// Translates an isogeny to an ideal using the Deuring correspondence.
///
/// Given an isogeny φ: E₀ → E, computes the corresponding left O₀-ideal I
/// where End(E₀) ≅ O₀.
pub fn isogeny_to_ideal(isogeny: &Isogeny, order: &MaximalOrder) -> LeftIdeal {
    // The ideal corresponding to φ is:
    // I_φ = {α ∈ O₀ : α(ker φ) = 0}
    //
    // This requires computing the action of endomorphisms on the kernel.

    // Simplified: create principal ideal with norm = degree
    let generator = Quaternion::new(
        Rational::from_int(isogeny.degree.clone()),
        Rational::zero(),
        Rational::zero(),
        Rational::zero(),
        order.p.clone(),
    );

    LeftIdeal::principal(order, generator)
}

/// KLPT algorithm for finding elements of specific norm in ideals.
///
/// Given an ideal I and target norm N, finds γ ∈ I with nrd(γ) = N
/// (or close to N with smooth factorization).
///
/// This is the key subroutine for SQI-SIGN: it allows converting
/// arbitrary ideals to equivalent ideals with smooth norm.
///
/// # Algorithm (Kohel-Lauter-Petit-Tignol)
///
/// 1. Compute a reduced basis for I using LLL or similar
/// 2. Use the Gram matrix to define a quadratic form Q(x) = nrd(Σ xᵢbᵢ)
/// 3. Enumerate lattice points with Q(x) = N using Fincke-Pohst or similar
/// 4. If exact match not found, find γ with smooth norm dividing N
///
/// # Strong Approximation
///
/// The algorithm uses strong approximation to ensure we can represent
/// any target norm that is coprime to p.
pub fn klpt(ideal: &LeftIdeal, target_norm: &BigInt) -> Option<Quaternion> {
    let p = &ideal.order.p;
    let basis = &ideal.basis;

    // Phase 1: Direct search for exact norm match
    if let Some(gamma) = search_exact_norm(basis, target_norm) {
        return Some(gamma);
    }

    // Phase 2: Try to find element with smooth norm that divides target
    if let Some(gamma) = search_smooth_divisor(basis, target_norm, p) {
        return Some(gamma);
    }

    // Phase 3: Strong approximation - find element close to target
    // using the quaternion norm equation: a² + b² + p(c² + d²) = N
    if let Some(gamma) = strong_approximation_search(basis, target_norm, p) {
        return Some(gamma);
    }

    // Phase 4: Fallback to extended brute-force search
    find_smooth_norm_element(ideal, target_norm)
}

/// Searches for an element with exactly the target norm.
fn search_exact_norm(basis: &[Quaternion; 4], target_norm: &BigInt) -> Option<Quaternion> {
    // Use expanding shell search to find small coefficient solutions
    for radius in 1..20i64 {
        for n0 in -radius..=radius {
            for n1 in -radius..=radius {
                for n2 in -radius..=radius {
                    for n3 in -radius..=radius {
                        // Skip if not on the shell boundary
                        let max_coeff = n0.abs().max(n1.abs()).max(n2.abs()).max(n3.abs());
                        if max_coeff != radius {
                            continue;
                        }

                        if n0 == 0 && n1 == 0 && n2 == 0 && n3 == 0 {
                            continue;
                        }

                        let gamma = linear_combination(
                            basis,
                            &[
                                BigInt::from(n0),
                                BigInt::from(n1),
                                BigInt::from(n2),
                                BigInt::from(n3),
                            ],
                        );

                        let norm = gamma.reduced_norm();
                        if norm.den == BigInt::one() && norm.num == *target_norm {
                            return Some(gamma);
                        }
                    }
                }
            }
        }
    }

    None
}

/// Searches for an element with smooth norm dividing the target.
fn search_smooth_divisor(
    basis: &[Quaternion; 4],
    target_norm: &BigInt,
    _p: &BigInt,
) -> Option<Quaternion> {
    let smoothness_bound = 50u64;

    for radius in 1..15i64 {
        for n0 in -radius..=radius {
            for n1 in -radius..=radius {
                let gamma = linear_combination(
                    basis,
                    &[
                        BigInt::from(n0),
                        BigInt::from(n1),
                        BigInt::zero(),
                        BigInt::zero(),
                    ],
                );

                if gamma.is_zero() {
                    continue;
                }

                let norm = gamma.reduced_norm();
                if norm.den != BigInt::one() || norm.num.is_zero() {
                    continue;
                }

                // Check if norm divides target and is smooth
                if target_norm % &norm.num == BigInt::zero()
                    && is_smooth(&norm.num, smoothness_bound)
                {
                    return Some(gamma);
                }
            }
        }
    }

    None
}

/// Uses strong approximation to find an element with the target norm.
///
/// Strong approximation theorem: Given N coprime to p, we can find
/// α ∈ B with nrd(α) = N by solving a² + b² + p(c² + d²) = N.
fn strong_approximation_search(
    _basis: &[Quaternion; 4],  // Reserved for future lattice-based optimization
    target_norm: &BigInt,
    p: &BigInt,
) -> Option<Quaternion> {
    // Try to express target_norm using the norm form
    // nrd(a + bi + cj + dk) = a² + b² + p·c² + p·d²

    // First check if we can solve a² + b² = N (mod p)
    // Then lift to a full solution

    let sqrt_n = target_norm.sqrt();
    let sqrt_n_i64 = sqrt_n.to_u64_digits().1.first().copied().unwrap_or(50).min(50) as i64;

    for a in 0..=sqrt_n_i64 {
        let a_sq = BigInt::from(a * a);
        if &a_sq > target_norm {
            break;
        }

        let remainder = target_norm - &a_sq;

        // Check if remainder can be written as b² + p(c² + d²)
        for b in 0..=sqrt_n_i64 {
            let b_sq = BigInt::from(b * b);
            if &b_sq > &remainder {
                break;
            }

            let pcd_sum = &remainder - &b_sq;
            if &pcd_sum % p != BigInt::zero() {
                continue;
            }

            let cd_sum = &pcd_sum / p;

            // Try to write cd_sum as c² + d²
            if let Some((c, d)) = two_squares(&cd_sum) {
                // Verify: a² + b² + p(c² + d²) = target
                let verify = &a_sq + &b_sq + p * (&c * &c + &d * &d);
                if &verify == target_norm {
                    // Found! Now find corresponding element in the ideal
                    let candidate = Quaternion::new(
                        Rational::from_int(BigInt::from(a)),
                        Rational::from_int(BigInt::from(b)),
                        Rational::from_int(c),
                        Rational::from_int(d),
                        p.clone(),
                    );

                    // Check if this is in the ideal (approximately)
                    // Return if norm matches
                    let norm = candidate.reduced_norm();
                    if norm.den == BigInt::one() && norm.num == *target_norm {
                        return Some(candidate);
                    }
                }
            }
        }
    }

    None
}

/// Represents n as a sum of two squares if possible: n = a² + b².
fn two_squares(n: &BigInt) -> Option<(BigInt, BigInt)> {
    if n < &BigInt::zero() {
        return None;
    }
    if n.is_zero() {
        return Some((BigInt::zero(), BigInt::zero()));
    }

    let sqrt_n = n.sqrt();
    let limit = sqrt_n.to_u64_digits().1.first().copied().unwrap_or(100).min(100) as i64;

    for a in 0..=limit {
        let a_sq = BigInt::from(a * a);
        if &a_sq > n {
            break;
        }

        let remainder = n - &a_sq;
        if let Some(b) = integer_sqrt(&remainder) {
            if &b * &b == remainder {
                return Some((BigInt::from(a), b));
            }
        }
    }

    None
}

/// Computes a linear combination of quaternions.
fn linear_combination(basis: &[Quaternion; 4], coeffs: &[BigInt; 4]) -> Quaternion {
    let p = basis[0].p.clone();
    let mut result = Quaternion::zero(p.clone());

    for (i, coeff) in coeffs.iter().enumerate() {
        let scaled = Quaternion::new(
            &basis[i].a * &Rational::from_int(coeff.clone()),
            &basis[i].b * &Rational::from_int(coeff.clone()),
            &basis[i].c * &Rational::from_int(coeff.clone()),
            &basis[i].d * &Rational::from_int(coeff.clone()),
            p.clone(),
        );
        result = result.add(&scaled);
    }

    result
}

/// Finds an element with smooth norm (product of small primes).
fn find_smooth_norm_element(ideal: &LeftIdeal, _target: &BigInt) -> Option<Quaternion> {
    // Try to find element whose norm is B-smooth and close to target
    // This is useful for constructing isogeny chains

    let basis = &ideal.basis;
    let smoothness_bound = 100u64;

    // Small search
    for n0 in 1..5i64 {
        for n1 in 0..3i64 {
            let gamma = linear_combination(
                basis,
                &[
                    BigInt::from(n0),
                    BigInt::from(n1),
                    BigInt::zero(),
                    BigInt::zero(),
                ],
            );

            let norm = gamma.reduced_norm();
            if norm.den == BigInt::one() && !norm.num.is_zero() {
                if is_smooth(&norm.num, smoothness_bound) {
                    return Some(gamma);
                }
            }
        }
    }

    None
}

/// Checks if n is B-smooth (all prime factors ≤ B).
fn is_smooth(n: &BigInt, bound: u64) -> bool {
    if n.is_zero() || n == &BigInt::one() {
        return true;
    }

    let mut remaining = if n < &BigInt::zero() { -n } else { n.clone() };

    // Trial division by small primes
    let small_primes: Vec<u64> = vec![2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47];

    for &p in &small_primes {
        if p > bound {
            break;
        }
        let prime = BigInt::from(p);
        while &remaining % &prime == BigInt::zero() {
            remaining = &remaining / &prime;
        }
    }

    remaining == BigInt::one()
}

/// Represents the response isogeny in compressed form.
///
/// For SQI-SIGN, we need to represent isogenies compactly.
#[derive(Clone, Debug)]
pub struct CompressedIdeal {
    /// Coefficients for the generator relative to order basis.
    pub coefficients: [BigInt; 4],
    /// The norm of the ideal.
    pub norm: BigInt,
}

impl CompressedIdeal {
    /// Compresses an ideal to its minimal representation.
    pub fn compress(ideal: &LeftIdeal) -> Self {
        // Extract generator coefficients (simplified)
        Self {
            coefficients: [
                ideal.basis[0].a.num.clone(),
                ideal.basis[0].b.num.clone(),
                ideal.basis[0].c.num.clone(),
                ideal.basis[0].d.num.clone(),
            ],
            norm: ideal.norm.clone(),
        }
    }

    /// Decompresses to a full ideal.
    pub fn decompress(&self, order: &MaximalOrder) -> LeftIdeal {
        let generator = Quaternion::new(
            Rational::from_int(self.coefficients[0].clone()),
            Rational::from_int(self.coefficients[1].clone()),
            Rational::from_int(self.coefficients[2].clone()),
            Rational::from_int(self.coefficients[3].clone()),
            order.p.clone(),
        );

        LeftIdeal::principal(order, generator)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_prime() -> BigInt {
        BigInt::from(431)
    }

    #[test]
    fn test_principal_ideal() {
        let p = test_prime();
        let order = MaximalOrder::standard(p.clone());

        // Create principal ideal generated by 1 + i
        let gen = Quaternion::new(
            Rational::from_int(BigInt::one()),
            Rational::from_int(BigInt::one()),
            Rational::zero(),
            Rational::zero(),
            p,
        );

        let ideal = LeftIdeal::principal(&order, gen);

        // Norm should be |nrd(1+i)| = |1 + 1| = 2
        assert_eq!(ideal.norm, BigInt::from(2));
    }

    #[test]
    fn test_ideal_conjugate() {
        let p = test_prime();
        let order = MaximalOrder::standard(p.clone());

        let gen = Quaternion::new(
            Rational::from_int(BigInt::one()),
            Rational::from_int(BigInt::from(2)),
            Rational::zero(),
            Rational::zero(),
            p,
        );

        let ideal = LeftIdeal::principal(&order, gen);
        let conj = ideal.conjugate();

        // Conjugate should have same norm
        assert_eq!(ideal.norm, conj.norm);
    }

    #[test]
    fn test_four_squares_small() {
        let p = test_prime();

        // 5 = 1² + 2² + 0² + 0² = 1 + 4
        if let Some((a, b, c, d)) = four_squares(&BigInt::from(5), &p) {
            let sum = &a * &a + &b * &b + &c * &c + &d * &d;
            assert_eq!(sum, BigInt::from(5));
        }
    }

    #[test]
    fn test_four_squares_larger() {
        let p = test_prime();

        // 30 should be representable
        if let Some((a, b, c, d)) = four_squares(&BigInt::from(30), &p) {
            let sum = &a * &a + &b * &b + &c * &c + &d * &d;
            assert_eq!(sum, BigInt::from(30));
        }
    }

    #[test]
    fn test_is_smooth() {
        assert!(is_smooth(&BigInt::from(1), 10));
        assert!(is_smooth(&BigInt::from(8), 10)); // 2³
        assert!(is_smooth(&BigInt::from(30), 10)); // 2 × 3 × 5
        assert!(!is_smooth(&BigInt::from(11), 10)); // 11 > 10
    }

    #[test]
    fn test_compressed_ideal() {
        let p = test_prime();
        let order = MaximalOrder::standard(p.clone());

        let gen = Quaternion::new(
            Rational::from_int(BigInt::from(3)),
            Rational::from_int(BigInt::from(4)),
            Rational::zero(),
            Rational::zero(),
            p,
        );

        let ideal = LeftIdeal::principal(&order, gen);
        let compressed = CompressedIdeal::compress(&ideal);
        let decompressed = compressed.decompress(&order);

        assert_eq!(ideal.norm, decompressed.norm);
    }

    #[test]
    fn test_ideal_to_isogeny() {
        let p = test_prime();
        let order = MaximalOrder::standard(p.clone());

        let gen = Quaternion::new(
            Rational::from_int(BigInt::from(2)),
            Rational::zero(),
            Rational::zero(),
            Rational::zero(),
            p,
        );

        let ideal = LeftIdeal::principal(&order, gen);
        let isogeny = ideal_to_isogeny(&ideal);

        // Isogeny degree should match ideal norm
        assert_eq!(isogeny.degree, ideal.norm);
    }
}
